{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.prometheus.name }}-service
  namespace: {{ include "autoscaler.namespace" . }}
  labels:
    {{- include "autoscaler.prometheus.labels" . | nindent 4 }}
spec:
  type: {{ .Values.prometheus.service.type }}
  selector:
    {{- include "autoscaler.prometheus.selectorLabels" . | nindent 4 }}
  ports:
  - port: {{ .Values.prometheus.port }}
    targetPort: {{ .Values.prometheus.port }}
    {{- if .Values.prometheus.service.nodePort }}
    nodePort: {{ .Values.prometheus.service.nodePort }}
    {{- end }}
    protocol: TCP
{{- end }}