apiVersion: v1
kind: Service
metadata:
  name: autoscaler-app-service
  namespace: autoscaling-ns
spec:
  type: LoadBalancer
  selector:
    app: autoscaler-app
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP