apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- app-deployment.yaml
- app-service.yaml
- prometheus/prometheus-deployment.yaml
- prometheus/prometheus-config.yaml
- prometheus/prometheus-service.yaml
- predictor-deployment.yaml
- hpa.yaml
- prometheus-adapter.yaml