{{- if .Values.prometheusAdapter.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.prometheusAdapter.name }}
  namespace: {{ include "autoscaler.namespace" . }}
  labels:
    {{- include "autoscaler.prometheusAdapter.labels" . | nindent 4 }}
{{- end }}