{{- if .Values.grafana.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.grafana.name }}
  namespace: {{ include "autoscaler.namespace" . }}
  labels:
    {{- include "autoscaler.grafana.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.grafana.replicas }}
  selector:
    matchLabels:
      {{- include "autoscaler.grafana.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "autoscaler.grafana.selectorLabels" . | nindent 8 }}
        {{- include "autoscaler.grafana.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.grafana.name }}
          image: "{{ .Values.grafana.image.repository }}:{{ .Values.grafana.image.tag }}"
          imagePullPolicy: {{ .Values.grafana.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.grafana.port }}
              protocol: TCP
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: {{ .Values.grafana.adminUser }}
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: {{ .Values.grafana.adminPassword }}
            - name: GF_INSTALL_PLUGINS
              value: ""
            - name: GF_PATHS_PROVISIONING
              value: /etc/grafana/provisioning
          volumeMounts:
            - name: datasource
              mountPath: /etc/grafana/provisioning/datasources
              readOnly: true
            - name: dashboards-provider
              mountPath: /etc/grafana/provisioning/dashboards
              readOnly: true
            - name: dashboards-data
              mountPath: /var/lib/grafana/dashboards
              readOnly: true
            {{- if .Values.grafana.storage.enabled }}
            - name: storage
              mountPath: /var/lib/grafana
            {{- end }}
          resources:
            {{- toYaml .Values.grafana.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /api/health
              port: {{ .Values.grafana.port }}
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health
              port: {{ .Values.grafana.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          {{- with .Values.grafana.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.grafana.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.grafana.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: datasource
          configMap:
            name: {{ .Values.grafana.name }}-datasource
        - name: dashboards-provider
          configMap:
            name: {{ .Values.grafana.name }}-dashboards-provider
        - name: dashboards-data
          configMap:
            name: {{ .Values.grafana.name }}-dashboard
        {{- if .Values.grafana.storage.enabled }}
        - name: storage
          persistentVolumeClaim:
            claimName: {{ .Values.grafana.name }}-pvc
        {{- end }}
{{- end }}